### ISSUE TITLE
How to remove background from "read-only" part of modeline?

### ISSUE THREAD

**Issue by lccambiaghi** [mclear-tools/bespoke-modeline#3]
<img width="414" alt="Screenshot 2022-02-06 at 22 54 43" src="https://user-images.githubusercontent.com/15185927/152702980-9208784b-756d-4727-b3e5-028ebb6fa376.png">

Hi, how can I remove the background of the right part of the modeline so that it has the same backrgound as the buffer name? Basically I would like to have the same behavior as in the screenshots.

Thank you for your great package!!

EDIT: oh also the right-most part (row number and column number) has the same background!

<img width="76" alt="Screenshot 2022-02-06 at 22 57 08" src="https://user-images.githubusercontent.com/15185927/152703032-bc34bc21-8357-4155-984b-0a4433ac5441.png">

**Comment by mclearc** [comment]
Hmm -- I can partially reproduce this. Can you check to see if the colors look correct after you run `bespoke-modeline-toggle`?

**Comment by mclearc** [comment]
In the short-term, you should be able to see the correct colors if you make sure that load bespoke-modeline _before_ you load bespoke-themes.

**Comment by mclearc** [comment]
Also -- it looks like you may not have a good font for displaying symbols. Check out Symbola font and the setup for it in the README if you'd like to the see the symbols display better.

**Comment by mclearc** [comment]
I also pushed a possible fix for this as well. See https://github.com/mclear-tools/bespoke-modeline/commit/d9a62ab2e36b890d14a94db4e723e34cb6421755.

**Comment by lccambiaghi** [comment]
Thank you! Loading bespoke-modeline before the themes worked like a charm!

EDIT: oh forgot to say I have installed Symbola with the instructions in the README but I still can't get the symbols to work. Any suggestions?
